baseurl = "http://dxy-developer.github.io/f2e/"
title = "丁香园前端小分队"
theme = "hyde"
hasCJKLanguage = true
relativeURLs = true

[params]
    DateFormat = "Mon, Jan 2, 2006"
    description = "说明文案说明文案说明文案说明文案"
    ShowRelatedPost = false
    SyntaxHighlightTheme = "solarized_dark.min.css"

[Indexes]
    tag = "tags"

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
[[menu.main]]
    name = "关于我们"
    url = "/aboutus/"
