baseurl = "http://dxy-developer.github.io/f2e"
title = "丁香园前端小分队"
copyright = "Establishment · 丁香园前端"
hasCJKLanguage = true

[params]
    DateFormat = "Mon, Jan 2, 2006"
    SubTitle = "DXY Tech&Product Division"
    comment = true
    [params.authors]
        acrens = "acrens.jpeg"
        alexayan = "alexayan.png"
        huot = "huot.jpg"
        "见见" = "jianjian.jpg"
        libr = "libr.png"
        "李小帅" = "xiaoshuai.jpg"
        wangxt = "wangxt.jpg"
        "阿wing" = "awing.jpg"
        yaoyj = "yaoyj.jpg"
        uojo = "uojo.jpg"
        "徐溯阳" = "xusy.png"

[indexes]
    tag = "tags"

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"


